services:
  watchtower:
    image: containrrr/watchtower:latest
    command: --interval 60 --include-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run
    networks:
      - flick-internal
      - flick-external
  backend:
    image: ghcr.io/flick-lang/flick-sandbox-backend:latest
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - flick-internal
    restart: always
  compiler:
    image: ghcr.io/flick-lang/flick-compiler:latest
    entrypoint: /bin/sh -c 'exit'
    restart: no


networks:
  flick-internal:
    internal: true
  flick-external:
    driver: bridge
