services:
  watchtower:
    image: containrrr/watchtower:latest
    command:
      - "--label-enable"
      - "--interval"
      - "60"
      - "--rolling-restart"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    command: tunnel run
    networks:
      - flick-internal
      - flick-external
  backend:
    image: ghcr.io/flick-lang/flick-sandbox-backend:latest
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - flick-internal
    restart: always
  flick-compiler:
    image: ghcr.io/flick-lang/flick-compiler:latest
    deploy:
      replicas: 0

networks:
  flick-internal:
    driver: bridge
  flick-external:
    driver: bridge
